# Generated by Django 2.0 on 2017-12-11 09:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('naver_work', '0002_navercafelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navercafelist',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
