# Generated by Django 2.0 on 2017-12-15 11:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('naver_work', '0003_navertask'),
    ]

    operations = [
        migrations.AddField(
            model_name='navertask',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
