# Generated by Django 2.0 on 2017-12-15 12:01

from django.db import migrations, models
import django_summernote.fields
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('naver_work', '0004_navertask_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navertask',
            name='naver_pw',
        ),
        migrations.AlterField(
            model_name='navertask',
            name='article',
            field=django_summernote.fields.SummernoteTextField(blank=True, default='내용을 입력해주세요.'),
        ),
        migrations.AlterField(
            model_name='navertask',
            name='cafe_address',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='navertask',
            name='cafe_board',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='navertask',
            name='cafe_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='navertask',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='navertask',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
