# Generated by Django 2.0 on 2017-12-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naver_work', '0005_auto_20171215_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navertask',
            name='article',
        ),
        migrations.RemoveField(
            model_name='navertask',
            name='cafe_address',
        ),
        migrations.RemoveField(
            model_name='navertask',
            name='cafe_board',
        ),
        migrations.RemoveField(
            model_name='navertask',
            name='cafe_name',
        ),
        migrations.RemoveField(
            model_name='navertask',
            name='naver_id',
        ),
        migrations.RemoveField(
            model_name='navertask',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='navertask',
            name='title',
        ),
        migrations.AddField(
            model_name='navertask',
            name='account',
            field=models.ManyToManyField(to='naver_work.NaverAccount'),
        ),
        migrations.AddField(
            model_name='navertask',
            name='cafe',
            field=models.ManyToManyField(to='naver_work.NaverCafeList'),
        ),
        migrations.AddField(
            model_name='navertask',
            name='post',
            field=models.ManyToManyField(to='naver_work.PostList'),
        ),
    ]
