# Generated by Django 2.0 on 2017-12-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naver_work', '0005_auto_20171212_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naveraccount',
            name='naver_blog',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='naveraccount',
            name='naver_pw',
            field=models.CharField(max_length=200),
        ),
    ]
