# Generated by Django 2.0 on 2017-12-12 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naver_work', '0006_auto_20171212_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='naveraccount',
            options={'ordering': ['-published_date']},
        ),
    ]
