# Generated by Django 2.0 on 2017-12-12 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('naver_work', '0007_auto_20171212_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navercafelist',
            name='author',
            field=models.ForeignKey(default='auth.User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
