# Generated by Django 2.0 on 2017-12-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naver_work', '0009_auto_20171212_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='naveraccount',
            name='naver_nick',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='naveraccount',
            name='naver_sex',
            field=models.CharField(choices=[('Men', '남자'), ('Women', '여자')], max_length=10),
        ),
    ]
