# Generated by Django 2.0 on 2017-12-12 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naver_work', '0012_auto_20171212_2250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postlist',
            options={'ordering': ['-published_date']},
        ),
    ]
