# Generated by Django 2.0 on 2017-12-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naver_work', '0013_auto_20171212_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlist',
            name='article',
            field=models.TextField(),
        ),
    ]
